openapi: 3.0.0
info:
  title: Recommendation API
  description: API to get recommendations for places, genres, and songs based on user input.
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
paths:
  /api/recommendations:
    post:
      summary: Get recommendations
      description: Retrieve recommendations for a place, genre, or song based on user input. This are limited to famous genres and cities.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                requestFor:
                  type: array
                  items:
                    type: string
                    enum: [song, genre]
                  description: List of types of recommendations requested.
                useAI:
                  type: boolean
                  description: Whether to use AI for recommendations.
                recommendation:
                  type: object
                  properties:
                    type:
                      type: string
                      enum: [place, song, genre]
                      description: The type of recommendation to fetch.
                    userInput:
                      type: string
                      description: The input value for which recommendations are needed.
              required:
                - requestFor
                - recommendation
      responses:
        '200':
          description: Successfully retrieved recommendations
          content:
            application/json:
              schema:
                type: object
                properties:
                  song:
                    type: string
                    description: Recommended song.
                  genre:
                    type: string
                    description: Recommended genre.
                  place:
                    type: string
                    description: Recommended place.
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
