version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Exposing port 3000 locally, nginx serves on 80 internally
    restart: unless-stopped
